# Generated by Django 4.0 on 2021-12-25 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_carrate_remove_car_avg_rating_alter_car_make_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CarRate',
        ),
        migrations.AddField(
            model_name='car',
            name='avg_rating',
            field=models.FloatField(default=1),
        ),
    ]
