# Generated by Django 4.0 on 2021-12-25 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_ratecalculate_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RateCalculate',
        ),
    ]
