# Generated by Django 4.0 on 2022-01-01 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_delete_ratecalculate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rating',
            options={'verbose_name_plural': ''},
        ),
        migrations.AddField(
            model_name='rating',
            name='car_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cars.car'),
        ),
        migrations.AlterField(
            model_name='car',
            name='avg_rating',
            field=models.FloatField(default=5),
        ),
        migrations.AlterField(
            model_name='car',
            name='make',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.TextField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Popular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.rating')),
            ],
        ),
    ]
